version: '3.7'

services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: vehicle
      POSTGRES_USER: user
      POSTGRES_PASSWORD: Admin123*
    volumes:
      - ./script/database.sql:/docker-entrypoint-initdb.d/database.sql
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/vehicle
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: Admin123*